// Restaurant and menu data
// Restaurant and menu data
const restaurantsData = {
    dominos: {
        id: "dominos",
        name: "Domino's Pizza",
        image: "https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg",
        rating: 4.2,
        deliveryTime: "25-30 mins",
        cuisine: "Pizzas, Italian, Fast Food",
        priceRange: "₹300 for two",
        discount: "50% OFF",
        menu: [
            {
                id: "dom_1",
                name: "Margherita Pizza",
                description: "Classic delight with 100% real mozzarella cheese.",
                price: 199,
                image: "https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg",
                category: "Pizza",
                veg: true,
            },
            {
                id: "dom_2",
                name: "Pepperoni Pizza",
                description: "American classic with pepperoni & cheese.",
                price: 349,
                image: "https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg",
                category: "Pizza",
                veg: false,
            },
            {
                id: "dom_3",
                name: "Chicken Dominator",
                description: "Loaded with grilled chicken chunks and spicy sauce.",
                price: 449,
                image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg",
                category: "Pizza",
                veg: false,
            },
            {
                id: "dom_4",
                name: "Garlic Bread",
                description: "Freshly baked garlic bread sticks with herbs.",
                price: 99,
                image: "https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg",
                category: "Sides",
                veg: true,
            },
            {
                id: "dom_5",
                name: "Choco Lava Cake",
                description: "Warm chocolate cake with molten center.",
                price: 89,
                image: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg",
                category: "Desserts",
                veg: true,
            },
            {
                id: "dom_6",
                name: "Farmhouse Pizza",
                description: "Loaded with fresh veggies like capsicum, onion, tomato, and mushrooms.",
                price: 299,
                image: "https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg",
                category: "Pizza",
                veg: true,
            },
            {
                id: "dom_7",
                name: "Paneer Tikka Pizza",
                description: "Spicy paneer tikka chunks on a cheesy pizza base.",
                price: 329,
                image: "https://images.pexels.com/photos/461382/pexels-photo-461382.jpeg",
                category: "Pizza",
                veg: true,
            },
            {
                id: "dom_8",
                name: "Cheese Burst Pizza",
                description: "Extra cheesy pizza with a creamy cheese-filled crust.",
                price: 379,
                image: "https://images.pexels.com/photos/2232/vegetables-italian-pizza-restaurant.jpg",
                category: "Pizza",
                veg: true,
            },
            {
                id: "dom_9",
                name: "Stuffed Garlic Bread",
                description: "Garlic bread stuffed with cheese and corn.",
                price: 129,
                image: "https://images.pexels.com/photos/461382/pexels-photo-461382.jpeg",
                category: "Sides",
                veg: true,
            },
            {
                id: "dom_10",
                name: "Peppy Paneer Pizza",
                description: "Paneer cubes, capsicum, and spicy red paprika.",
                price: 319,
                image: "https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg",
                category: "Pizza",
                veg: true,
            },
        ],
    },
    mcdonalds: {
        id: "mcdonalds",
        name: "McDonald's",
        image: "https://images.pexels.com/photos/4676410/pexels-photo-4676410.jpeg",
        rating: 4.1,
        deliveryTime: "20-25 mins",
        cuisine: "Burgers, Fast Food, American",
        priceRange: "₹400 for two",
        discount: "30% OFF",
        menu: [
            {
                id: "mcd_1",
                name: "Big Mac",
                description: "Two all-beef patties, special sauce, lettuce, cheese.",
                price: 189,
                image: "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg",
                category: "Burgers",
                veg: false,
            },
            {
                id: "mcd_2",
                name: "McChicken Burger",
                description: "Crispy chicken patty with mayo and lettuce.",
                price: 149,
                image: "https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg",
                category: "Burgers",
                veg: false,
            },
            {
                id: "mcd_3",
                name: "French Fries",
                description: "Golden crispy fries with sea salt.",
                price: 89,
                image: "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg",
                category: "Sides",
                veg: true,
            },
            {
                id: "mcd_4",
                name: "McFlurry Oreo",
                description: "Vanilla soft serve with Oreo cookie pieces.",
                price: 119,
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/a28369e386195be4071d9cf5078a438d",
                category: "Desserts",
                veg: true,
            },
            {
                id: "mcd_5",
                name: "Coca Cola",
                description: "Refreshing cola drink.",
                price: 59,
                image: "https://images.pexels.com/photos/50593/coca-cola-cold-drink-soft-drink-coke-50593.jpeg",
                category: "Beverages",
                veg: true,
            },
            {
                id: "mcd_6",
                name: "McVeggie Burger",
                description: "Vegetable patty with lettuce and mayo.",
                price: 139,
                image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
                category: "Burgers",
                veg: true,
            },
            {
                id: "mcd_7",
                name: "Chicken Nuggets",
                description: "Tender chicken pieces with dipping sauce.",
                price: 149,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Sides",
                veg: false,
            },
            {
                id: "mcd_8",
                name: "Veg Pizza McPuff",
                description: "Crispy puff filled with spicy veggie pizza filling.",
                price: 69,
                image: "https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg",
                category: "Snacks",
                veg: true,
            },
            {
                id: "mcd_9",
                name: "Spicy Paneer Wrap",
                description: "Crispy paneer with spicy dressing in a wrap.",
                price: 179,
                image: "https://images.pexels.com/photos/1095550/pexels-photo-1095550.jpeg",
                category: "Wraps",
                veg: true,
            },
            {
                id: "mcd_10",
                name: "Strawberry Shake",
                description: "Creamy strawberry milkshake.",
                price: 99,
                image: "https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg",
                category: "Beverages",
                veg: true,
            },
        ],
    },
    kfc: {
        id: "kfc",
        name: "KFC",
        image: "https://onlykutts.com/wp-content/uploads/2021/11/KFC-logo.jpeg",
        rating: 4.0,
        deliveryTime: "30-35 mins",
        cuisine: "Chicken, Fast Food, American",
        priceRange: "₹450 for two",
        discount: "40% OFF",
        menu: [
            {
                id: "kfc_1",
                name: "Original Recipe Chicken",
                description: "Secret blend of 11 herbs and spices.",
                price: 199,
                image: "https://images.pexels.com/photos/2233348/pexels-photo-2233348.jpeg",
                category: "Chicken",
                veg: false,
            },
            {
                id: "kfc_2",
                name: "Zinger Burger",
                description: "Spicy chicken fillet burger.",
                price: 179,
                image: "https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg",
                category: "Burgers",
                veg: false,
            },
            {
                id: "kfc_3",
                name: "Popcorn Chicken",
                description: "Bite-sized pieces of tender chicken.",
                price: 149,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Chicken",
                veg: false,
            },
            {
                id: "kfc_4",
                name: "Coleslaw",
                description: "Fresh cabbage and carrot salad.",
                price: 79,
                image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
                category: "Sides",
                veg: true,
            },
            {
                id: "kfc_5",
                name: "Krushems",
                description: "Thick shake with cookie crumbs.",
                price: 129,
                image: "https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg",
                category: "Beverages",
                veg: true,
            },
            {
                id: "kfc_6",
                name: "Hot & Crispy Chicken",
                description: "Crispy fried chicken with spicy coating.",
                price: 209,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Chicken",
                veg: false,
            },
            {
                id: "kfc_7",
                name: "Chicken Bucket",
                description: "Assorted fried chicken pieces in a bucket.",
                price: 499,
                image: "https://images.pexels.com/photos/2233348/pexels-photo-2233348.jpeg",
                category: "Chicken",
                veg: false,
            },
            {
                id: "kfc_8",
                name: "Veg Zinger Burger",
                description: "Spicy veg patty with lettuce and mayo.",
                price: 159,
                image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
                category: "Burgers",
                veg: true,
            },
            {
                id: "kfc_9",
                name: "Peri Peri Chicken Strips",
                description: "Spicy peri peri marinated chicken strips.",
                price: 179,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Chicken",
                veg: false,
            },
            {
                id: "kfc_10",
                name: "Chocolate Lava Cake",
                description: "Rich chocolate cake with molten chocolate center.",
                price: 129,
                image: "https://images.pexels.com/photos/533325/pexels-photo-533325.jpeg",
                category: "Desserts",
                veg: true,
            },
        ],
    },
    paradise: {
        id: "paradise",
        name: "Paradise Biryani",
        image: "https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg",
        rating: 4.5,
        deliveryTime: "30-40 mins",
        cuisine: "Biryani, North Indian, Hyderabadi",
        priceRange: "₹500 for two",
        discount: "10% OFF",
        menu: [
            {
                id: "par_1",
                name: "Chicken Dum Biryani",
                description: "Aromatic basmati rice and chicken cooked on dum.",
                price: 350,
                image: "https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg",
                category: "Biryani",
                veg: false,
            },
            {
                id: "par_2",
                name: "Mutton Biryani",
                description: "Tender mutton pieces in fragrant rice.",
                price: 450,
                image: "https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg",
                category: "Biryani",
                veg: false,
            },
            {
                id: "par_3",
                name: "Paneer Biryani",
                description: "Soft paneer cubes in a flavorful biryani.",
                price: 300,
                image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/02/paneer-biryani-recipe.jpg",
                category: "Biryani",
                veg: true,
            },
            {
                id: "par_4",
                name: "Chicken 65",
                description: "Spicy, deep-fried chicken appetizer.",
                price: 250,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Starters",
                veg: false,
            },
            {
                id: "par_5",
                name: "Double Ka Meetha",
                description: "A sweet bread pudding from Hyderabad.",
                price: 150,
                image: "https://x9s2d6a3.delivery.rocketcdn.me/wp-content/uploads/2018/04/double-ka-meetha-25_1200x1200.jpg",
                category: "Desserts",
                veg: true,
            },
            {
                id: "par_6",
                name: "Egg Biryani",
                description: "Basmati rice cooked with boiled eggs and spices.",
                price: 280,
                image: "https://images.pexels.com/photos/12737656/pexels-photo-12737656.jpeg",
                category: "Biryani",
                veg: true,
            },
            {
                id: "par_7",
                name: "Veg Biryani",
                description: "Mixed vegetables cooked with aromatic rice and spices.",
                price: 250,
                image: "https://www.indianveggiedelight.com/wp-content/uploads/2020/04/veg-biryani-instant-pot.jpg",
                category: "Biryani",
                veg: true,
            },
            {
                id: "par_8",
                name: "Mirchi Ka Salan",
                description: "Hyderabadi spicy chili curry served with biryani.",
                price: 120,
                image: "https://ranveerbrar.com/wp-content/uploads/2021/02/Baingan-mirchi-ka-salan.jpg",
                category: "Sides",
                veg: true,
            },
            {
                id: "par_9",
                name: "Raita",
                description: "Cool yogurt raita with cucumber and spices.",
                price: 60,
                image: "https://www.indianveggiedelight.com/wp-content/uploads/2017/06/cucumber-raita-recipe-featured.jpg",
                category: "Sides",
                veg: true,
            },
            {
                id: "par_10",
                name: "Gulab Jamun",
                description: "Soft milk balls soaked in sugar syrup.",
                price: 90,
                image: "https://i0.wp.com/www.chitrasfoodbook.com/wp-content/uploads/2016/10/gulab-jamun-using-mix.jpg?w=1200&ssl=1",
                category: "Desserts",
                veg: true,
            },
        ],
    },
    pizzahut: {
        id: "pizzahut",
        name: "Pizza Hut",
        image: "https://b.zmtcdn.com/data/pictures/chains/5/3000095/0279cb06f7b0151a1da07ea593ba7fec_featured_v2.jpg",
        rating: 4.1,
        deliveryTime: "30-35 mins",
        cuisine: "Pizzas, Italian, Fast Food",
        priceRange: "₹400 for two",
        discount: "60% OFF",
        menu: [
            {
                id: "ph_1",
                name: "Supreme Pizza",
                description: "Loaded with pepperoni, sausage, and vegetables.",
                price: 399,
                image: "https://images.pexels.com/photos/708587/pexels-photo-708587.jpeg",
                category: "Pizza",
                veg: false,
            },
            {
                id: "ph_2",
                name: "Veggie Supreme",
                description: "Fresh vegetables with mozzarella cheese.",
                price: 349,
                image: "https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg",
                category: "Pizza",
                veg: true,
            },
            {
                id: "ph_3",
                name: "Chicken Wings",
                description: "Spicy buffalo chicken wings.",
                price: 249,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Sides",
                veg: false,
            },
            {
                id: "ph_4",
                name: "Pasta Alfredo",
                description: "Creamy white sauce pasta.",
                price: 199,
                image: "https://images.pexels.com/photos/1279330/pexels-photo-1279330.jpeg",
                category: "Pasta",
                veg: true,
            },
            {
                id: "ph_5",
                name: "Brownie",
                description: "Warm chocolate brownie with ice cream.",
                price: 129,
                image: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg",
                category: "Desserts",
                veg: true,
            },
            {
                id: "ph_6",
                name: "Pepperoni Lover's Pizza",
                description: "Loaded with extra pepperoni and cheese.",
                price: 399,
                image: "https://images.pexels.com/photos/1146760/pexels-photo-1146760.jpeg",
                category: "Pizza",
                veg: false,
            },
            {
                id: "ph_7",
                name: "Tandoori Paneer Pizza",
                description: "Paneer cubes marinated in tandoori spices on a pizza.",
                price: 359,
                image: "https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg",
                category: "Pizza",
                veg: true,
            },
            {
                id: "ph_8",
                name: "Garlic Breadsticks",
                description: "Soft breadsticks with garlic butter.",
                price: 99,
                image: "https://images.pexels.com/photos/4109111/pexels-photo-4109111.jpeg",
                category: "Sides",
                veg: true,
            },
            {
                id: "ph_9",
                name: "Cheesy Momo Pizza",
                description: "Fusion pizza topped with cheesy momos.",
                price: 299,
                image: "https://images.pexels.com/photos/1435907/pexels-photo-1435907.jpeg",
                category: "Pizza",
                veg: true,
            },
            {
                id: "ph_10",
                name: "Classic Veg Pizza",
                description: "Simple pizza with tomato, onion, and capsicum.",
                price: 249,
                image: "https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg",
                category: "Pizza",
                veg: true,
            },
        ],
    },
    burgerking: {
        id: "burgerking",
        name: "Burger King",
        image: "https://www.livelaw.in/h-upload/2024/08/19/556384-burger-king.jpg",
        rating: 4.0,
        deliveryTime: "25-30 mins",
        cuisine: "Burgers, Fast Food, American",
        priceRange: "₹350 for two",
        discount: "25% OFF",
        menu: [
            {
                id: "bk_1",
                name: "Whopper",
                description: "Flame-grilled beef patty with fresh ingredients.",
                price: 219,
                image: "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg",
                category: "Burgers",
                veg: false,
            },
            {
                id: "bk_2",
                name: "Chicken Royale",
                description: "Crispy chicken breast with mayo.",
                price: 189,
                image: "https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg",
                category: "Burgers",
                veg: false,
            },
            {
                id: "bk_3",
                name: "Onion Rings",
                description: "Golden crispy onion rings.",
                price: 99,
                image: "https://images.pexels.com/photos/4676410/pexels-photo-4676410.jpeg",
                category: "Sides",
                veg: true,
            },
            {
                id: "bk_4",
                name: "Chicken Nuggets",
                description: "Tender chicken pieces with dipping sauce.",
                price: 149,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Chicken",
                veg: false,
            },
            {
                id: "bk_5",
                name: "Vanilla Shake",
                description: "Creamy vanilla milkshake.",
                price: 109,
                image: "https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.bs/files/BK_WEB_VANILLASHAKE_500x540.png",
                category: "Beverages",
                veg: true,
            },
            {
                id: "bk_6",
                name: "Veg Whopper",
                description: "Veg patty with fresh lettuce, tomato, and mayo.",
                price: 179,
                image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
                category: "Burgers",
                veg: true,
            },
            {
                id: "bk_7",
                name: "Crispy Chicken Burger",
                description: "Crispy chicken fillet with spicy sauce.",
                price: 169,
                image: "https://images.pexels.com/photos/1633578/pexels-photo-1633578.jpeg",
                category: "Burgers",
                veg: false,
            },
            {
                id: "bk_8",
                name: "French Fries",
                description: "Classic salted fries.",
                price: 89,
                image: "https://images.pexels.com/photos/1583884/pexels-photo-1583884.jpeg",
                category: "Sides",
                veg: true,
            },
            {
                id: "bk_9",
                name: "Chocolate Shake",
                description: "Rich chocolate milkshake.",
                price: 119,
                image: "https://bk-latam-prod.s3.amazonaws.com/sites/burgerking.bs/files/BK_WEB_CHOCSHAKE_500x540.png",
                category: "Beverages",
                veg: true,
            },
            {
                id: "bk_10",
                name: "Paneer King Burger",
                description: "Spicy paneer patty with fresh veggies.",
                price: 159,
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTAgXREV8iNWgoXds81plZF3ppassq36U2bPQ&s",
                category: "Burgers",
                veg: true,
            },
        ],
    },
    saravanabhavan: {
        id: "saravanabhavan",
        name: "Saravana Bhavan",
        image: "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/tm7txdyckvgpmxunpzh1",
        rating: 4.6,
        deliveryTime: "25-35 mins",
        cuisine: "South Indian, Vegetarian",
        priceRange: "₹400 for two",
        discount: "15% OFF",
        menu: [
            {
                id: "sb_1",
                name: "Masala Dosa",
                description: "Crispy Dosa crepe with a savory potato filling.",
                price: 150,
                image: "https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg",
                category: "Dosa",
                veg: true,
            },
            {
                id: "sb_2",
                name: "Idli Sambar",
                description: "Steamed rice cakes served with lentil soup.",
                price: 100,
                image: "https://dineout-media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto/DINEOUT_ALL_RESTAURANTS/IMAGES/RESTAURANT_IMAGE_SERVICE/2024/7/23/24cd7c71-13b0-4ea4-83dc-52925b93b536_20240723T060113327.PNG",
                category: "Idli",
                veg: true,
            },
            {
                id: "sb_3",
                name: "Pongal",
                description: "A savory rice and lentil dish.",
                price: 120,
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/8/11/c0f34829-16c3-4953-91fb-6d4c556f8b35_8049c14c-15d1-4955-8114-ae569061688e.jpeg",
                category: "South Indian",
                veg: true,
            },
            {
                id: "sb_4",
                name: "Filter Coffee",
                description: "Traditional South Indian filter coffee.",
                price: 50,
                image: "https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg",
                category: "Beverages",
                veg: true,
            },
            {
                id: "sb_5",
                name: "Rava Kesari",
                description: "A sweet semolina dessert.",
                price: 80,
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/6/14/434f4113-ae9f-497d-9fb6-f353325242a2_3ef2e0cd-6ebf-4ea9-b9fb-04a35df2b5cb.jpg",
                category: "Desserts",
                veg: true,
            },
            {
                id: "sb_6",
                name: "Gobi Manchurian",
                description: "Crispy cauliflower tossed in spicy sauce.",
                price: 220,
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2024/3/21/37f8667c-7f72-4fca-a105-a1e5dc4b0676_30949bb5-3675-40fb-b561-e9b2714eda99.jpg",
                category: "Starters",
                veg: true,
            },
            {
                id: "sb_7",
                name: "Gobi 65",
                description: "Deep-fried cauliflower with South Indian spices.",
                price: 195,
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_240,h_240/FOOD_CATALOG/IMAGES/CMS/2025/5/17/048f9a69-9701-49a7-9358-009435b71c19_1feefbce-b172-4731-8212-e0b076700778.jpg_compressed",
                category: "Starters",
                veg: true,
            },
            {
                id: "sb_8",
                name: "Chilli Paneer",
                description: "Paneer cubes tossed in spicy chili sauce.",
                price: 210,
                image: "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/hwklevkgwztxpsitqba4",
                category: "Starters",
                veg: true,
            },
            {
                id: "sb_9",
                name: "Paneer Fried Rice",
                description: "Fried rice with paneer and vegetables.",
                price: 190,
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/522296599515accaa41fc29c25be493a",
                category: "Rice",
                veg: true,
            },
            {
                id: "sb_10",
                name: "Mushroom Dum Biryani",
                description: "Basmati rice cooked with mushrooms and spices.",
                price: 135,
                image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_300,h_300,c_fit/FOOD_CATALOG/IMAGES/CMS/2025/1/18/7bbefcda-99de-498d-9132-bc1877431aea_a9acd251-c6a7-4cee-b202-e238179d5c7a.JPG",
                category: "Biryani",
                veg: true,
            },
        ],
    },
    albaik: {
        id: "albaik",
        name: "Street Arabiya Shawarma",
        image: "https://streetarabiya.com/wp-content/uploads/2024/04/sa-website-logo-1-1024x274.png",
        rating: 4.4,
        deliveryTime: "20-30 mins",
        cuisine: "Shawarma, Arabian, Fast Food",
        priceRange: "₹300 for two",
        discount: "20% OFF",
        menu: [
            {
                id: "ab_1",
                name: "Chicken Shawarma",
                description: "Grilled chicken wrapped in pita bread.",
                price: 120,
                image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
                category: "Shawarma",
                veg: false,
            },
            {
                id: "ab_2",
                name: "Mutton Shawarma",
                description: "Tender mutton wrapped in pita bread.",
                price: 150,
                image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
                category: "Shawarma",
                veg: false,
            },
            {
                id: "ab_3",
                name: "Falafel Shawarma",
                description: "Crispy falafel balls in a wrap.",
                price: 100,
                image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
                category: "Shawarma",
                veg: true,
            },
            {
                id: "ab_4",
                name: "Hummus with Pita",
                description: "Creamy hummus served with fresh pita bread.",
                price: 80,
                image: "https://www.electroluxarabia.com/globalassets/elux-arabia/inspiration/recipe/hummus-with-pita-bread_x3rl.jpg",
                category: "Sides",
                veg: true,
            },
            {
                id: "ab_5",
                name: "Fresh Lime Soda",
                description: "A refreshing citrus drink.",
                price: 60,
                image: "https://images.squarespace-cdn.com/content/v1/5e628436fff16f203dd5da72/1591020757007-DQO3GDKHSL50L0L6YSZF/LimeSoda%281%29.jpg",
                category: "Beverages",
                veg: true,
            },
            {
                id: "ab_6",
                name: "Grilled Chicken Plate",
                description: "Juicy grilled chicken served with salad and bread.",
                price: 180,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Starters",
                veg: false,
            },
            {
                id: "ab_7",
                name: "Shish Tawook",
                description: "Marinated chicken skewers grilled to perfection.",
                price: 160,
                image: "https://www.anediblemosaic.com/wp-content/uploads//2021/07/shish-taouk-chicken-recipe-featured-image.jpg",
                category: "Starters",
                veg: false,
            },
            {
                id: "ab_8",
                name: "Veg Shawarma",
                description: "Mixed vegetables wrapped in pita bread.",
                price: 90,
                image: "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg",
                category: "Shawarma",
                veg: true,
            },
            {
                id: "ab_9",
                name: "Chicken Kebab",
                description: "Spiced chicken kebabs served with dip.",
                price: 140,
                image: "https://images.pexels.com/photos/60616/fried-chicken-chicken-fried-crunchy-60616.jpeg",
                category: "Starters",
                veg: false,
            },
            {
                id: "ab_10",
                name: "Baklava",
                description: "Sweet pastry made of layers of filo filled with nuts.",
                price: 110,
                image: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg",
                category: "Desserts",
                veg: true,
            },
        ],
    },
    keralaparottacorner: {
        id: "keralaparottacorner",
        name: "Kerala Parotta Corner",
        image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS24Psh1uyHuwMuubb0sB6WsIq80w--k-zFWQ&s",
        rating: 4.3,
        deliveryTime: "25-30 mins",
        cuisine: "Kerala, South Indian",
        priceRange: "₹250 for two",
        discount: "25% OFF",
        menu: [
            {
                id: "kpc_1",
                name: "Malabar Parotta",
                description: "Layered flatbread from Kerala.",
                price: 30,
                image: "https://www.chefkunalkapur.com/wp-content/uploads/2021/05/Malabar-Paratha-1300x867.jpg?v=1620281813",
                category: "Parotta",
                veg: true,
            },
            {
                id: "kpc_2",
                name: "Chicken Curry",
                description: "Spicy chicken curry to go with parotta.",
                price: 150,
                image: "https://kitchenofdebjani.com/wp-content/uploads/2023/04/easy-indian-chicken-curry-Recipe-for-beginners-Debjanir-rannaghar.jpg",
                category: "Curries",
                veg: false,
            },
            {
                id: "kpc_3",
                name: "Egg Curry",
                description: "Boiled eggs in a flavorful gravy.",
                price: 120,
                image: "https://static01.nyt.com/images/2020/03/04/dining/tr-egg-curry/merlin_169211805_227972c0-43d1-4f25-9643-9568331d8adb-mediumSquareAt3X.jpg",
                category: "Curries",
                veg: true,
            },
            {
                id: "kpc_4",
                name: "Beef Fry",
                description: "Spicy and dry beef fry, a Kerala specialty.",
                price: 180,
                image: "https://maldivescook.com/wp-content/uploads/beef-curry.jpg",
                category: "Starters",
                veg: false,
            },
            {
                id: "kpc_5",
                name: "Sulaimani Chai",
                description: "A special black tea from Malabar.",
                price: 40,
                image: "https://cookingfromheart.com/wp-content/uploads/2020/08/Sulaimani-Tea-5.jpg",
                category: "Beverages",
                veg: true,
            },
            {
                id: "kpc_6",
                name: "Vegetable Stew",
                description: "Kerala style mixed vegetable stew in coconut milk.",
                price: 110,
                image: "https://feelgoodfoodie.net/wp-content/uploads/2024/12/Vegetable-Stew-10.jpg",
                category: "Curries",
                veg: true,
            },
            {
                id: "kpc_7",
                name: "Fish Curry",
                description: "Spicy Kerala fish curry with coconut and tamarind.",
                price: 160,
                image: "https://vismaifood.com/storage/app/uploads/public/daa/96d/7bc/thumb__700_0_0_0_auto.jpg",
                category: "Curries",
                veg: false,
            },
            {
                id: "kpc_8",
                name: "Avial",
                description: "Mixed vegetables cooked in coconut and yogurt.",
                price: 90,
                image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTzcRGtjqP5cPVj5JWDurTfnJozO5noRZrZJw&s",
                category: "Sides",
                veg: true,
            },
            {
                id: "kpc_9",
                name: "Banana Chips",
                description: "Crispy Kerala style banana chips.",
                price: 60,
                image: "https://www.agarwalbhavansweets.com/cdn/shop/files/Banana_Chips.png?v=1711620702",
                category: "Snacks",
                veg: true,
            },
            {
                id: "kpc_10",
                name: "Payasam",
                description: "Traditional Kerala dessert made with milk and rice.",
                price: 80,
                image: "https://www.sharmispassions.com/wp-content/uploads/2023/10/sago-payasam01-500x500.jpg",
                category: "Desserts",
                veg: true,
            },
        ],
    },
    baskinrobbins: {
        id: "baskinrobbins",
        name: "Baskin Robbins",
        image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
        rating: 4.3,
        deliveryTime: "20-25 mins",
        cuisine: "Ice Cream, Desserts, Beverages",
        priceRange: "₹300 for two",
        discount: "30% OFF",
        menu: [
            {
                id: "br_1",
                name: "Vanilla Ice Cream",
                description: "Classic vanilla ice cream scoop.",
                price: 89,
                image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
                category: "Ice Cream",
                veg: true,
            },
            {
                id: "br_2",
                name: "Chocolate Fudge",
                description: "Rich chocolate ice cream with fudge.",
                price: 109,
                image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
                category: "Ice Cream",
                veg: true,
            },
            {
                id: "br_3",
                name: "Strawberry Sundae",
                description: "Strawberry ice cream with toppings.",
                price: 149,
                image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
                category: "Sundae",
                veg: true,
            },
            {
                id: "br_4",
                name: "Milkshake",
                description: "Thick vanilla milkshake.",
                price: 129,
                image: "https://images.pexels.com/photos/103566/pexels-photo-103566.jpeg",
                category: "Beverages",
                veg: true,
            },
            {
                id: "br_5",
                name: "Ice Cream Cake",
                description: "Celebration ice cream cake slice.",
                price: 199,
                image: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg",
                category: "Cakes",
                veg: true,
            },
            {
                id: "br_6",
                name: "Mango Ice Cream",
                description: "Creamy mango flavored ice cream.",
                price: 99,
                image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
                category: "Ice Cream",
                veg: true,
            },
            {
                id: "br_7",
                name: "Butterscotch Ice Cream",
                description: "Crunchy butterscotch ice cream scoop.",
                price: 109,
                image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
                category: "Ice Cream",
                veg: true,
            },
            {
                id: "br_8",
                name: "Black Currant Ice Cream",
                description: "Tangy black currant ice cream.",
                price: 119,
                image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
                category: "Ice Cream",
                veg: true,
            },
            {
                id: "br_9",
                name: "Chocolate Brownie Sundae",
                description: "Chocolate ice cream with brownie chunks and sauce.",
                price: 159,
                image: "https://images.pexels.com/photos/291528/pexels-photo-291528.jpeg",
                category: "Sundae",
                veg: true,
            },
            {
                id: "br_10",
                name: "Fruit Overload",
                description: "Mixed fruit ice cream with real fruit pieces.",
                price: 139,
                image: "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg",
                category: "Ice Cream",
                veg: true,
            },
        ],
    },
};


// Categories data
const categoriesData = [
    {
        "id": "pizza",
        "name": "Pizza",
        "image": "https://images.pexels.com/photos/2147491/pexels-photo-2147491.jpeg"
    },
    {
        "id": "burgers",
        "name": "Burgers",
        "image": "https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg"
    },
    {
        "id": "biryani",
        "name": "Biryani",
        "image": "https://images.pexels.com/photos/1624487/pexels-photo-1624487.jpeg"
    },
    {
        "id": "southindian",
        "name": "South Indian",
        "image": "https://images.pexels.com/photos/5560763/pexels-photo-5560763.jpeg"
    },
    {
        "id": "shawarma",
        "name": "Shawarma",
        "image": "https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg"
    },
    {
        "id": "parotta",
        "name": "Parotta",
        "image": "https://c.ndtvimg.com/2021-05/tj7sdqj8_parotta_625x300_14_May_21.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=675"
    },
    {
        "id": "chicken",
        "name": "Chicken",
        "image": "https://www.spiceindiaonline.com/wp-content/uploads/2021/05/Tandoori-Chicken-20.jpg"
    },
    {
        "id": "icecream",
        "name": "Ice Cream",
        "image": "https://images.pexels.com/photos/1362534/pexels-photo-1362534.jpeg"
    }
];

// Save data to localStorage for fast retrieval
function saveDataToLocalStorage() {
    localStorage.setItem('restaurantsData', JSON.stringify(restaurantsData));
    localStorage.setItem('categoriesData', JSON.stringify(categoriesData));
}

// Load data from localStorage
function loadDataFromLocalStorage() {
    const restaurants = localStorage.getItem('restaurantsData');
    const categories = localStorage.getItem('categoriesData');
    
    if (restaurants && categories) {
        return {
            restaurants: JSON.parse(restaurants),
            categories: JSON.parse(categories)
        };
    }
    
    // If no data in localStorage, save current data
    saveDataToLocalStorage();
    return {
        restaurants: restaurantsData,
        categories: categoriesData
    };
}

// Initialize data
saveDataToLocalStorage();
